# Generated by Django 6.1.1 on 2026-09-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('specialties', models.CharField(help_text='Comma separated specialties', max_length=255)),
                ('is_partner', models.BooleanField(default=False, help_text='Gets negotiated/discounted rates for our patients')),
                ('partner_discount_percentage', models.PositiveSmallIntegerField(default=0)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost_min', models.PositiveIntegerField(help_text='Approx. minimum cost in INR')),
                ('estimated_cost_max', models.PositiveIntegerField(help_text='Approx. maximum cost in INR')),
                ('notes', models.TextField(blank=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_recommendations', to='treatments.condition')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['estimated_cost_min'],
            },
        ),
    ]
