# Generated by Django 6.1.1 on 2026-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospitalapplication_hospitalapplicationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
