upstream lalaharihealth_api {
    server unix:/run/lalaharihealth/api.sock fail_timeout=0;
}

server {
    listen 80;
    server_name lalaharihealth.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 80;
    server_name api.lalaharihealth.com;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name lalaharihealth.com;

    ssl_certificate /etc/letsencrypt/live/lalaharihealth.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lalaharihealth.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://127.0.0.1:3101;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 443 ssl;
    server_name api.lalaharihealth.com;
    client_max_body_size 10M;

    ssl_certificate /etc/letsencrypt/live/lalaharihealth.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lalaharihealth.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /static/ {
        alias /srv/lalaharihealth/backend/staticfiles/;
    }

    location /media/ {
        alias /srv/lalaharihealth/backend/media/;
    }

    location / {
        proxy_pass http://lalaharihealth_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
