# Generated by Django 6.1.1 on 2026-09-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('allopathy', 'Allopathic'), ('homeopathy', 'Homeopathic'), ('ayurveda', 'Ayurvedic'), ('unani', 'Unani'), ('home_remedy', 'Home Remedy')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('estimated_cost_min', models.PositiveIntegerField(help_text='Approx. minimum cost in INR')),
                ('estimated_cost_max', models.PositiveIntegerField(help_text='Approx. maximum cost in INR')),
                ('is_recommended', models.BooleanField(default=False, help_text='Doctor-recommended default option')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_options', to='treatments.condition')),
            ],
            options={
                'ordering': ['condition', 'system'],
            },
        ),
    ]
