# Generated by Django 6.1.1 on 2026-09-23 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=150)),
                ('systems_practiced', models.CharField(help_text='Comma separated TreatmentSystem values this doctor consults on', max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('consultation_fee', models.PositiveIntegerField(help_text='Fee in INR')),
                ('languages_spoken', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('degree_certificate', 'Degree Certificate'), ('medical_registration', 'Medical Council Registration'), ('government_id', 'Government ID'), ('other', 'Other')], max_length=25)),
                ('file', models.FileField(upload_to='doctors/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctors.doctorprofile')),
            ],
        ),
    ]
