# Generated by Django 6.1.1 on 2026-09-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('qualification', models.CharField(help_text='e.g. MBBS, BAMS, MD (Ayurveda)', max_length=255)),
                ('experience_years', models.PositiveSmallIntegerField()),
                ('specialization', models.CharField(max_length=150)),
                ('treatment_systems', models.JSONField(default=list, help_text='Selected TreatmentSystem values')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_priority', models.BooleanField(default=True, help_text='Pre-launch registrants get priority status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='doctor_applications/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='doctors.doctorapplication')),
            ],
        ),
    ]
