# Generated by Django 6.1.1 on 2026-10-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctorapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorapplication',
            name='consultation_category',
            field=models.CharField(choices=[('general', 'General Physician / General Doctor'), ('specialist', 'Specialist')], default='general', max_length=12),
        ),
        migrations.AddField(
            model_name='doctorapplication',
            name='consultation_fee',
            field=models.PositiveSmallIntegerField(default=200, help_text='Consultation fee in INR'),
        ),
    ]
